export const selectPhoto = (state) => state.posts.photo;
export const selectPhotoName = (state) => state.posts.photoName;
export const selectLocationName = (state) => state.posts.locationName;
export const selectCurrentLocation = (state) => state.posts.currentLocation;
export const selectUserId = (state) => state.posts.userId;
export const selectLikes = (state) => state.posts.likes;
export const selectPosts = (state) => state.posts.posts;
export const selectPostsForLastWeek = (state) => state.posts.postsForLastWeek;
export const selectComments = (state) => state.posts.comments;